### ISSUE TITLE
Add "Car Drawing Game"

### ISSUE THREAD

**Issue by PriceyLamp** [ericksoncohen/radon-games#40]
**Car Drawing Game**
The name of the game you want to request.

**A game where you must draw a car that can pass certain obstacles to get to the end of the level**
A brief description of the game (so we add the right one).

**https://www.coolmathgames.com > 0-car-drawing-game**
The URL of the game's website or a playable version of the game.

**Additional information**
Add any other information about the game here.

**Comment by cohenerickson** [comment]
Moved to Discord https://discord.gg/t3d7wDA9WY
